### PR TITLE
Add libxml2212 migration + 2.10.0

### PR DESCRIPTION
**Pull request by hmaarrfk**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Review by ilya-lavrenov — APPROVED** [review]

**Comment by isuruf** [comment]
Let's just wait for https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/634

**Comment by hmaarrfk** [comment]
@isuruf given you are active at the moment, would you consider merging this so that ilya's work can move one step forward today?

I think you will want a 2.10.0 update to this package in either case so it won't really hurt.

also please see: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5385

**Comment by isuruf** [comment]
I don't know if doing both at the same time is a good idea.

**Comment by hmaarrfk** [comment]
Ok i understand. I figured i would ask either way.

Thanks for your help on this front.

**Pull request closed without merging**
