### PR TITLE
Add AMD support 

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
Somehow the windows test failed, but this seems to be unrelated to the changes in this pull request: 
```
C:\Program Files\Microsoft Visual Studio\2022\Enterprise>CALL "VC\Auxiliary\Build\vcvars64.bat" -vcvars_ver=14.29 10.0.22621.0 
**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.6.4
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
You need to run patch_libtool bash function after configure to fix the libtool script.
If your package uses OpenMP, add llvm-openmp to your host and run requirements.
make: *** No targets specified and no makefile found.  Stop.
```

**Comment by jan-janssen** [comment]
@isuruf Unfortunately, the windows tests still fail with the same error - can you take a look?

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by isuruf** [comment]
@jan-janssen, when you cherry-pick my commits, please use my name and email as the author for the git commit in the future.

**Comment by jan-janssen** [comment]
> @jan-janssen, when you cherry-pick my commits, please use my name and email as the author for the git commit in the future.

Sure, thanks for the heads up

**Pull request merged**
