### PR TITLE
 Rebuild for CUDA 11.8 w/arch support with additional fix for out of space issue

### PR DESCRIPTION
**Pull request by traversaro**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
Now it fails with:
~~~
2023-09-28T14:31:02.8474028Z clang.exe -DHAVE_CONFIG_H -I. -I../../include/private/autogen -I../../include/hwloc/autogen  -I"/d/bld/libhwloc_1695910688784/work"/include -I"/d/bld/libhwloc_1695910688784/work"/include -I../../utils/hwloc  -DLSTOPO_HAVE_GRAPHICS -ID:/bld/libhwloc_1695910688784/_h_env/Library/include -O2 -D_CRT_SECURE_NO_WARNINGS -D_MT -D_DLL -nostdlib -Xclang --dependent-lib=msvcrt -fuse-ld=lld -Dputenv=_putenv -Dmktemp=_mktemp -Dopen=_open -Dunlink=_unlink -Dclose=_close -Dstrdup=_strdup  -mwindows -ID:/bld/libhwloc_1695910688784/_h_env/Library/include -O2 -D_CRT_SECURE_NO_WARNINGS -D_MT -D_DLL -nostdlib -Xclang --dependent-lib=msvcrt -fuse-ld=lld -c -o lstopo_win-lstopo.o `test -f 'lstopo.c' || echo './'`lstopo.c
2023-09-28T14:31:03.2085724Z clang: error: unsupported option '-mwindows' for target 'x86_64-pc-windows-msvc'
~~~

An error that was not there in https://github.com/conda-forge/libhwloc-feedstock/pull/67 .

**Comment by traversaro** [comment]
> clang: error: unsupported option '-mwindows'

Probably this is due to the new clang: https://github.com/llvm/llvm-project/issues/64464 .

**Comment by jakirkham** [comment]
Looks like that should be fixed in Clang 17.0.2: https://github.com/llvm/llvm-project-release-prs/commit/f6cf58eed9737cb8718465c4fb6917ca854b1bc3

There's already a feedstock update PR: https://github.com/conda-forge/clangdev-feedstock/pull/245

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
> Looks like that should be fixed in Clang 17.0.2: [llvm/llvm-project-release-prs@f6cf58e](https://github.com/llvm/llvm-project-release-prs/commit/f6cf58eed9737cb8718465c4fb6917ca854b1bc3)
> 
> There's already a feedstock update PR: [conda-forge/clangdev-feedstock#245](https://github.com/conda-forge/clangdev-feedstock/pull/245)

Perfect, thanks! I removed the workaround.

**Comment by jakirkham** [comment]
Hmm...I guess since we are still on 16 (and presumably that fix hasn't been backported), we still need a workaround

**Comment by traversaro** [comment]
> Hmm...I guess since we are still on 16 (and presumably that fix hasn't been backported), we still need a workaround

But the workaround was to use `clang 16`, see https://github.com/conda-forge/libhwloc-feedstock/pull/69/commits/6173f7c2fc1739c14bec931017b563981b5f37a7 . Anyhow, it was working, let's try to put it back.

**Comment by traversaro** [comment]
> Hmm...I guess since we are still on 16 (and presumably that fix hasn't been backported), we still need a workaround

Actually the CI is installing 17, and somehow there is the -mwindows failure also on clang 17.0.2 . I don't think we are fixing clang on Windows? Anyhow, fixing clang to 16 was working, let's try again that.

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
> Looks like that should be fixed in Clang 17.0.2: [llvm/llvm-project-release-prs@f6cf58e](https://github.com/llvm/llvm-project-release-prs/commit/f6cf58eed9737cb8718465c4fb6917ca854b1bc3)
> 
> There's already a feedstock update PR: [conda-forge/clangdev-feedstock#245](https://github.com/conda-forge/clangdev-feedstock/pull/245)

Looking more at that, I am not sure if that is related, as that seems to be related to llvm with the mingw frontend (i.e. the one used in https://github.com/mstorsjo/llvm-mingw), while here we use the msvc frontend. I am not sure if we should open an issue in llvm for our problem.

**Comment by jakirkham** [comment]
Think that is unrelated. Our `clang` builds happen [here]( https://github.com/conda-forge/clangdev-feedstock/blob/6c53d61ad422ee5612f751bc437f9beb221e6b91/recipe/meta.yaml#L384 ), which just uses [the LLVM sources]( https://github.com/conda-forge/clangdev-feedstock/blob/6c53d61ad422ee5612f751bc437f9beb221e6b91/recipe/meta.yaml#L23 )

It looks like we were pulling in Clang 17 before when it was unpinned [on CI]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=797999&view=logs&jobId=4356d191-3d4f-5b9e-9fff-749e4103d7dd&j=4356d191-3d4f-5b9e-9fff-749e4103d7dd&t=c5f66fe7-8b5b-58fc-ad9a-e9f627515fd9 )

```
    clang:                 17.0.2-h3dc180e_0         conda-forge
    clang-17:              17.0.2-default_heb8d277_0 conda-forge
    clangxx:               17.0.2-default_heb8d277_0 conda-forge
```

Am now wondering why that wasn't working 🤔

**Comment by traversaro** [comment]
> Think that is unrelated. Our clang builds happen [here](https://github.com/conda-forge/clangdev-feedstock/blob/6c53d61ad422ee5612f751bc437f9beb221e6b91/recipe/meta.yaml#L384), which just uses [the LLVM sources](https://github.com/conda-forge/clangdev-feedstock/blob/6c53d61ad422ee5612f751bc437f9beb221e6b91/recipe/meta.yaml#L23)

Not sure what you were referring with this sentence.

> Am now wondering why that wasn't working 🤔

I think there is an issue _similar_ to https://github.com/llvm/llvm-project/issues/64464, but related to the MSVC toolchain, so it is not affected by the fix in https://github.com/llvm/llvm-project-release-prs/commit/f6cf58eed9737cb8718465c4fb6917ca854b1bc3, that is mingw toolchain specific. However, the problem could be on the libhwloc side, as `-mwindows` may be a flag that does not make sense for the msvc toolchain of clang, and just by chance this was working on clang <= 16 .

**Comment by jakirkham** [comment]
Maybe I'm misunderstanding something, but it seems like there are a bunch of MinGW components pulled into this build. So thought we might be trying to build with MinGW (hence the MinGW bug looked appropriate). Again I might be misunderstanding things

**Comment by jakirkham** [comment]
Filed issue ( https://github.com/llvm/llvm-project/issues/69964 ) for the MSVC case

**Comment by jakirkham** [comment]
From upstream:

>> However, the problem could be on the libhwloc side, as -mwindows may be a flag that does not make sense for the msvc toolchain of clang, and just by chance this was working on clang <= 16 .
>
> That's exactly the case.

Sounds like a `libhwloc` issue then. Can see they [add `-mwindows` on this line]( https://github.com/open-mpi/hwloc/blob/fed97f603afc0a8fab2c6f846e3fda9f54f6e0d1/utils/lstopo/Makefile.am#L63 ). Maybe it needs a guard to check whether MinGW or MSVC is used

**Comment by traversaro** [comment]
Thanks for digging on this @jakirkham !

**Comment by jakirkham** [comment]
@traversaro ofc! Feel free to chime in on issue ( https://github.com/llvm/llvm-project/issues/69964 ) if you have more info that would help

Sounds like we can merge this and follow up on anything else after ( cc @conda-forge/libhwloc )

**Review by jan-janssen — APPROVED** [review]
Looks good to me

**Comment by RaulPPelaez** [comment]
Hi guys, thanks for the good work! could we merge this?

**Comment by jakirkham** [comment]
Thanks all! 🙏

**Pull request merged**
