### PR TITLE
Rename cuda package

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
I tried to follow @isuruf 's suggestions in https://github.com/conda-forge/libhwloc-feedstock/pull/46 and https://github.com/conda-forge/libhwloc-feedstock/pull/53 to update the naming of the individual sub packages.

**Comment by jan-janssen** [comment]
@isuruf The tests passed, can you take a look if these changes correctly address your comments?

**Comment by isuruf** [comment]
Thanks. We need to mark the old cuda package as broken for track_features to work correctly.

**Comment by jan-janssen** [comment]
> Thanks. We need to mark the old cuda package as broken for track_features to work correctly.

I opened a pull request to mark the intermediate builds 1-5 as broken https://github.com/conda-forge/admin-requests/pull/728

**Pull request merged**
